# Generated by Django 4.1.7 on 2023-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payments_sender', models.CharField(blank=True, max_length=100, null=True)),
                ('Payments_reciever', models.CharField(blank=True, max_length=100, null=True)),
                ('Payments_date', models.DateTimeField(blank=True, null=True)),
                ('Payments_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
