# Generated by Django 4.1.7 on 2023-04-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Vehicle_BookingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
