# Generated by Django 4.1.7 on 2023-04-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0007_auto_20210307_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_name',
        ),
    ]
