# Generated by Django 4.1.7 on 2023-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0008_remove_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_initial_location',
            field=models.CharField(default='IIIT Kalyani', max_length=200),
        ),
    ]
