# Generated by Django 4.1.7 on 2023-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0009_vehicle_vehicle_initial_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_initial_location',
            field=models.CharField(default='IIIT Kalyani Manual', max_length=200),
        ),
    ]
