# Generated by Django 4.1.7 on 2023-04-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentVehicle', '0004_auto_20210309_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehicle',
            old_name='Advance_amount',
            new_name='Amount_tobePaid',
        ),
    ]
