# Generated by Django 4.1.7 on 2023-04-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentVehicle', '0006_rentvehicle_rentvehicle_droplocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehicle',
            old_name='Amount_tobePaid',
            new_name='Amount_Paid',
        ),
    ]
