# Generated by Django 4.1.7 on 2023-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20210303_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='Manager_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
